### ISSUE TITLE
Reason: 'failed to simulate for instructions'

### ISSUE THREAD

**Issue by codesys2023** [chainstacklabs/raydium-sdk-swap-example-typescript#10]
Hello All,
I am not able to understand why I am getting this error while executing swap through Raydium sdk.
I have followed all the steps mentioned in the Readme and changed all the configs accordingly.
Still facing this issue.
![solerror](https://github.com/chainstacklabs/raydium-sdk-swap-example-typescript/assets/139235190/655822ef-4fbb-4213-9bee-2d0116328376)

**Comment by soos3d** [comment]
It looks like an error from the RPC. Which RPC are you using? I have never received this error before.
