### ISSUE TITLE
The calculated exchange amount is sometimes small

### ISSUE THREAD

**Issue by jsmzr** [chainstacklabs/raydium-sdk-swap-example-typescript#11]
- sol swap usdc, 0.02 WSOL -> 0.38 (It should be 2.x)
- slippage 5%
- mainnet tx: [FVGsLj53u5sGKpDZYePZPiUV23SqGCQrVDYYM1cj1auSRcBENKAsotdhJgpXugawrZZxRttt5KS1tG3bU3BCuFo](https://solscan.io/tx/FVGsLj53u5sGKpDZYePZPiUV23SqGCQrVDYYM1cj1auSRcBENKAsotdhJgpXugawrZZxRttt5KS1tG3bU3BCuFo)

Should I also check the price and get a new pool info if it differs too much from expectations

Log at exception time, Liquidity.computeAmountOut
```txt
[DEBUG] slippage: 5%
[DEBUG] input side: base
[DEBUG] currentPrice: 1 UNKNOWN ≈ 146.953173 UNKNOWN
[DEBUG] currentPrice invert: 1 UNKNOWN ≈ 0.006804889 UNKNOWN
[DEBUG] amountOut: 0.418642
[DEBUG] minAmountOut: 0.398706
[DEBUG] executionPrice: 1 UNKNOWN ≈ 20.984561 UNKNOWN
[DEBUG] executionPrice invert: 1 UNKNOWN ≈ 0.047654082 UNKNOWN
[DEBUG] priceImpact: 85.72%
```
Normal time logs, Liquidity.computeAmountOut
```txt
[DEBUG] slippage: 5%
[DEBUG] input side: base
[DEBUG] currentPrice: 1 UNKNOWN ≈ 147.345628 UNKNOWN
[DEBUG] currentPrice invert: 1 UNKNOWN ≈ 0.006786764 UNKNOWN
[DEBUG] amountOut: 2.927112
[DEBUG] minAmountOut: 2.787725
[DEBUG] executionPrice: 1 UNKNOWN ≈ 146.722406 UNKNOWN
[DEBUG] executionPrice invert: 1 UNKNOWN ≈ 0.006815592 UNKNOWN
[DEBUG] priceImpact: 0.42297%
```

**Comment by cc-l-x** [comment]
hello.  sir。I  can't see any print info in this function Liquidity.computeAmountOut,but I can see a lot of  logger.debug like this     logger.debug('baseReserve:', baseReserve.toString()) logger.debug('quoteReserve:', quoteReserve.toString()).   so. how can i see the log print like above?

**Comment by cc-l-x** [comment]
兄弟。有空吗 能不能帮忙解释一下为啥我的运行结果里面没有那些log的打印呢

**Comment by jsmzr** [comment]
> 兄弟。有空吗 能不能帮忙解释一下为啥我的运行结果里面没有那些log的打印呢

使用 `@raydium-io/raydium-sdk` 你可以通过 `Logger` 进行设置
```ts
import { Logger } from "@raydium-io/raydium-sdk";

Logger.setLogLevel('Liquidity', 'DEBUG');
```

如果你使用的是 `@raydium-io/raydium-sdk-v2`，你可以使用 `setLoggerLevel` 设置
```ts
import { setLoggerLevel, LogLevel } from '@raydium-io/raydium-sdk-v2';

setLoggerLevel('Raydium', LogLevel.Debug);
```
