### ISSUE TITLE
Transaction Signed but not appearing on solscan

### ISSUE THREAD

**Issue by umaid56** [chainstacklabs/raydium-sdk-swap-example-typescript#12]
I am using the Raydium script to swap transactions, and I'm currently testing on the mainnet. but each time I do this, I receive a transaction hash. However, when I copy and paste this hash for verification, it shows nothing. Additionally, no tokens appear in my wallet, nor is any SOL deducted. When I run the script again with the same code, it attempts to swap again. Could this issue be due to the low amount I am swapping, or is there another problem?

https://solscan.io/tx/2fy1tsER1KbcYp6hPeWQGxmvipFV7kyEZHprug5VhcesvyBMBiEL8TJ1dLuj6hu62criv9t9qm6Xuv4qzJneHf5X

**Comment by elroydo** [comment]
Same issue on my end

**Comment by miaoluyao** [comment]
me too

**Comment by fafaly** [comment]
always happens，what should i do?

**Comment by akegaviar** [comment]
Hey guys, I updated the project to only use the trimmed version of mainnet.json. Details here https://github.com/chainstacklabs/raydium-sdk-swap-example-typescript/blob/main/README.md#tldr-quick-run

I did a test and it runs the transaction is executed. Feel free to check again.
