### ISSUE TITLE
The liquidityFile is too large. Is there a faster way to get the poolInfo from two tokens?

### ISSUE THREAD

**Issue by y0unghe** [chainstacklabs/raydium-sdk-swap-example-typescript#14]
Whenever the swap executes the program will call the following codes to get the `poolInfo`  to load the liquidity file. The file is 467MB. Is there a better and faster way to get the `poolInfo`?

```
await raydiumSwap.loadPoolKeys(Raydium_Liquidity_File);

let poolInfo = raydiumSwap.findPoolInfoForTokens(sourceToken, destinationToken);
```

**Comment by mukul013** [comment]
You are right , did you find any other way to find be poolInfo faster ?

**Comment by akegaviar** [comment]
Hey guys, a valid point. I updated the project to only use the trimmed version. Check the TLDR quick run section as it has the details https://github.com/chainstacklabs/raydium-sdk-swap-example-typescript/blob/main/README.md#tldr-quick-run

**Comment by ultravigilante** [comment]
```
❯ ts-node ./trimMainnet.ts
Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.readFileSync (node:fs:441:20)
    at trimMainnetJson (/home/me/repos/work/raydium-sdk-swap-example-typescript/src/trimMainnet.ts:31:39)
    at Object.<anonymous> (/home/me/repos/work/raydium-sdk-swap-example-typescript/src/trimMainnet.ts:58:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module.m._compile (/home/me/.local/share/mise/installs/node/22.8.0/lib/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Object.require.extensions.<computed> [as .ts] (/home/me/.local/share/mise/installs/node/22.8.0/lib/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14) {
  code: 'ERR_STRING_TOO_LONG'
}
```

Unsure if this is OS specific or not, I'm using Arch Linux and Node v22.8.0.

In my main project I'm using JSONStream to load the JSON in chunks rather than loading the full file at once. Maybe something similar should be done for the trim script?

**Comment by kuchaguangjie** [comment]
> ```
> ❯ ts-node ./trimMainnet.ts
> Error: Cannot create a string longer than 0x1fffffe8 characters
>     at Object.readFileSync (node:fs:441:20)
>     at trimMainnetJson (/home/me/repos/work/raydium-sdk-swap-example-typescript/src/trimMainnet.ts:31:39)
>     at Object.<anonymous> (/home/me/repos/work/raydium-sdk-swap-example-typescript/src/trimMainnet.ts:58:1)
>     at Module._compile (node:internal/modules/cjs/loader:1546:14)
>     at Module.m._compile (/home/me/.local/share/mise/installs/node/22.8.0/lib/node_modules/ts-node/src/index.ts:1618:23)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
>     at Object.require.extensions.<computed> [as .ts] (/home/me/.local/share/mise/installs/node/22.8.0/lib/node_modules/ts-node/src/index.ts:1621:12)
>     at Module.load (node:internal/modules/cjs/loader:1317:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:1127:12)
>     at TracingChannel.traceSync (node:diagnostics_channel:315:14) {
>   code: 'ERR_STRING_TOO_LONG'
> }
> ```
> 
> Unsure if this is OS specific or not, I'm using Arch Linux and Node v22.8.0. Looks like the file is just too big for Node.js at >512MiB.
> 
> In my main project I'm using JSONStream to load the JSON in chunks rather than loading the full file at once. Maybe something similar should be done for the trim script?

same error on ubuntu 24.04

should re-open this

**Comment by cbeauch** [comment]
Same error for me
