### ISSUE TITLE
Loaded pool keys

### ISSUE THREAD

**Issue by 0NighTWizard0** [chainstacklabs/raydium-sdk-swap-example-typescript#2]
hello.
I don't know why it gives me this error when I exceute the swap.
this error related to the pool and it's like the code can't read the pool list.

Loaded pool keys
C:\raydium-sdk-swap-example-typescript\src\RaydiumSwap.ts:59
    const poolData = this.allPoolKeysJson.find(
                                          ^
TypeError: Cannot read properties of undefined (reading 'find')
    at RaydiumSwap.findPoolInfoForTokens (C:\raydium-sdk-swap-example-typescript\src\RaydiumSwap.ts:59:43)
    at C:\raydium-sdk-swap-example-typescript\src\index.ts:30:32
    at Generator.next (<anonymous>)
    at fulfilled (C:\raydium-sdk-swap-example-typescript\src\index.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by 1500256797** [comment]
i met same error 
`    const directionIn = poolKeys.quoteMint.toString() == toToken
                                 ^
TypeError: Cannot read properties of null (reading 'quoteMint')`

**Comment by soos3d** [comment]
I have been noticing this error with new coins. Are you trying to swap newly created coins?

**Comment by 0NighTWizard0** [comment]
its BOME token (ukHH6c7mMyiWCf1b9pnWe25TSpkDDt3H5pQZgZ74J82)
it came about 6 days ago.

**Comment by soos3d** [comment]
just tried it now and the simulation worked fine!

```
Raydium swap initialized
Swapping 0.01 of So11111111111111111111111111111111111111112 for ukHH6c7mMyiWCf1b9pnWe25TSpkDDt3H5pQZgZ74J82...
Loaded pool keys
Found pool info
{
  minAmountOut: TokenAmount {
    numerator: <BN: 7c19b44>,
    denominator: <BN: f4240>,
    currency: Token {
      decimals: 6,
      symbol: 'UNKNOWN',
      name: 'UNKNOWN',
      programId: [PublicKey [PublicKey(TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA)]],
      mint: [PublicKey [PublicKey(ukHH6c7mMyiWCf1b9pnWe25TSpkDDt3H5pQZgZ74J82)]]
    },
    token: Token {
      decimals: 6,
      symbol: 'UNKNOWN',
      name: 'UNKNOWN',
      programId: [PublicKey [PublicKey(TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA)]],
      mint: [PublicKey [PublicKey(ukHH6c7mMyiWCf1b9pnWe25TSpkDDt3H5pQZgZ74J82)]]
    }
  },
  amountIn: TokenAmount {
    numerator: <BN: 989680>,
    denominator: <BN: 3b9aca00>,
    currency: Token {
      decimals: 9,
      symbol: 'UNKNOWN',
      name: 'UNKNOWN',
      programId: [PublicKey [PublicKey(TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA)]],
      mint: [PublicKey [PublicKey(So11111111111111111111111111111111111111112)]]
    },
    token: Token {
      decimals: 9,
      symbol: 'UNKNOWN',
      name: 'UNKNOWN',
      programId: [PublicKey [PublicKey(TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA)]],
      mint: [PublicKey [PublicKey(So11111111111111111111111111111111111111112)]]
    }
  }
}
{
  context: { apiVersion: '1.17.25', slot: 255567497 },
  value: {
    accounts: null,
    err: null,
    logs: [
      'Program ComputeBudget111111111111111111111111111111 invoke [1]',
      'Program ComputeBudget111111111111111111111111111111 success',
      'Program 11111111111111111111111111111111 invoke [1]',
      'Program 11111111111111111111111111111111 success',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]',
      'Program log: Instruction: InitializeAccount',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3443 of 999700 compute units',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
      'Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]',
      'Program log: Create',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]',
      'Program log: Instruction: GetAccountDataSize',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1569 of 986390 compute units',
      'Program return: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA pQAAAAAAAAA=',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
      'Program 11111111111111111111111111111111 invoke [2]',
      'Program 11111111111111111111111111111111 success',
      'Program log: Initialize the associated token account',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]',
      'Program log: Instruction: InitializeImmutableOwner',
      'Program log: Please upgrade to SPL Token 2022 for immutable owner support',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1405 of 979803 compute units',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]',
      'Program log: Instruction: InitializeAccount3',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4188 of 975921 compute units',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
      'Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 24807 of 996257 compute units',
      'Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success',
      'Program 675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8 invoke [1]',
      'Program log: ray_log: A4CWmAAAAAAARJvBBwAAAAABAAAAAAAAAICWmAAAAAAAeylzdg8AAACMAmQgAQAAAAjjJAgAAAAA',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]',
      'Program log: Instruction: Transfer',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4736 of 953333 compute units',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]',
      'Program log: Instruction: Transfer',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4645 of 945616 compute units',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
      'Program 675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8 consumed 31282 of 971450 compute units',
      'Program 675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8 success',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]',
      'Program log: Instruction: CloseAccount',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2915 of 940168 compute units',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success'
    ],
    returnData: null,
    unitsConsumed: 62747
  }
}
✨  Done in 21.39s.
```

**Comment by youngclaude** [comment]
> i met same error ` const directionIn = poolKeys.quoteMint.toString() == toToken ^ TypeError: Cannot read properties of null (reading 'quoteMint')`

@soos3d Thanks for your help on this. Its clear the community will use it to trade the latest meme craze of the hour so the acceptance tests should be tight to that use case. 

I was able to swap with your default example tokens with no issues using my mainnet Chainstack RPC.

However I am seeing the same issue as others after changing the 'tokenBAddress' address. Did you change anything to get it to work? Here is an example with the Raydium token RAY
 
![image](https://github.com/chainstacklabs/raydium-sdk-swap-example-typescript/assets/15623401/927c4be8-938d-4cc4-9474-68668597cfe1)

**Comment by mulerm** [comment]
> I have been noticing this error with new coins. Are you trying to swap newly created coins?

This is nice tool. Thanks! I'm trying this with newly created coins and I see the same error. Is this because it attempts to read the price of the token? Why not provide an option for the user to specify?

**Comment by peonante** [comment]
I have the same problem, it would be interesting to have a solution for swapping new tokens too

**Comment by soos3d** [comment]
> > i met same error ` const directionIn = poolKeys.quoteMint.toString() == toToken ^ TypeError: Cannot read properties of null (reading 'quoteMint')`
> 
> @soos3d Thanks for your help on this. Its clear the community will use it to trade the latest meme craze of the hour so the acceptance tests should be tight to that use case.
> 
> I was able to swap with your default example tokens with no issues using my mainnet Chainstack RPC.
> 
> However I am seeing the same issue as others after changing the 'tokenBAddress' address. Did you change anything to get it to work? Here is an example with the Raydium token RAY
> 
> ![image](https://private-user-images.githubusercontent.com/15623401/315839844-927c4be8-938d-4cc4-9474-68668597cfe1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDY5NjksIm5iZiI6MTcxMTU0NjY2OSwicGF0aCI6Ii8xNTYyMzQwMS8zMTU4Mzk4NDQtOTI3YzRiZTgtOTM4ZC00Y2M0LTk0NzQtNjg2Njg1OTdjZmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDEzMzc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2YmI2OWVmN2NjMzM0NTdmNTY4YmMzOGE3YTZmYTcxNGE1MDczYzJlYWQxY2U0Y2RkZjM0ZDE1MWMzNzFmNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7aCUJkOOWgHNYopcn8PngrzLt7T5mZiaaqxcSAhk698)

Hi @youngclaude , `quoteMint` should be an issue with the slippage. You can edit it from here: [slippage line](https://github.com/chainstacklabs/raydium-sdk-swap-example-typescript/blob/dfc55a9d1852d51bae5c40ed75f0d595552e7f72/src/RaydiumSwap.ts#L252)

**Comment by soos3d** [comment]
I'm working on adding retries to re-fetch the pools when they fail. might not fix the issue at 100%, but it should help.

**Comment by peonante** [comment]
> > > i met same error ` const directionIn = poolKeys.quoteMint.toString() == toToken ^ TypeError: Cannot read properties of null (reading 'quoteMint')`
> > 
> > 
> > @soos3d Thanks for your help on this. Its clear the community will use it to trade the latest meme craze of the hour so the acceptance tests should be tight to that use case.
> > I was able to swap with your default example tokens with no issues using my mainnet Chainstack RPC.
> > However I am seeing the same issue as others after changing the 'tokenBAddress' address. Did you change anything to get it to work? Here is an example with the Raydium token RAY
> > ![image](https://private-user-images.githubusercontent.com/15623401/315839844-927c4be8-938d-4cc4-9474-68668597cfe1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDY5NjksIm5iZiI6MTcxMTU0NjY2OSwicGF0aCI6Ii8xNTYyMzQwMS8zMTU4Mzk4NDQtOTI3YzRiZTgtOTM4ZC00Y2M0LTk0NzQtNjg2Njg1OTdjZmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDEzMzc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2YmI2OWVmN2NjMzM0NTdmNTY4YmMzOGE3YTZmYTcxNGE1MDczYzJlYWQxY2U0Y2RkZjM0ZDE1MWMzNzFmNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7aCUJkOOWgHNYopcn8PngrzLt7T5mZiaaqxcSAhk698)
> 
> Hi @youngclaude , `quoteMint` should be an issue with the slippage. You can edit it from here: [slippage line](https://github.com/chainstacklabs/raydium-sdk-swap-example-typescript/blob/dfc55a9d1852d51bae5c40ed75f0d595552e7f72/src/RaydiumSwap.ts#L252)

I tried changing the slippage but nothing changes, the error persists.

I believe the problem is due to the fact that new pairs are not immediately updated in the .. mainnet.json link

**Comment by soos3d** [comment]
Yes, I think that too. Adding retry logic to fetch the pairs should make it better. I'll work on it as soon as I have some time!

**Comment by peonante** [comment]
must there be something already existing that does this job? I can't find any other repositories or code anywhere that solves this, yet there are swaps and bots that do it

**Comment by kiknaio** [comment]
Hey folks :wave: I have same issue. 
I'm trying to get pool information from here `https://api.raydium.io/v2/sdk/liquidity/mainnet.json` and seems Raydium is updating file not so frequently and one can't get latest deployed pool information from there. 
Do you know any alternative services that provide that?

**Comment by anisurrahman072** [comment]
Guys thanks a lot for your helps. Is there any way to test it first on devnet ?

Why my change "https://api.raydium.io/v2/sdk/liquidity/devnet.json" not works ? @soos3d could you please let me know how can i make the code compatible for Devnet ?

Doing test by Devnet is important really.

**Comment by Krshivam25** [comment]
I swapped the token A (HUMP). to token B (SOL) the terminal show no error and generate the transaction URL but [TX-URL_SOLSCAN](https://solscan.io/tx/MHsDbkop1UE1rpKY8NmaT5HwzHHzRJf5yS9K7DMNy7kHTnv2g9CjFRCstrzjvtaBkvZVBuh1si28qTC9kXXvTfR) nothing is there

**Comment by soos3d** [comment]
> Guys thanks a lot for your helps. Is there any way to test it first on devnet ?
> 
> Why my change "https://api.raydium.io/v2/sdk/liquidity/devnet.json" not works ? @soos3d could you please let me know how can i make the code compatible for Devnet ?
> 
> Doing test by Devnet is important really.

Let me look into that!

**Comment by Krshivam25** [comment]
@soos3d adding to this code need lot of more improvement as even the user dont have the SOL balance on wallet the transaction getting executed and there is no check for this. which is wrong.

**Comment by soos3d** [comment]
>even the user dont have the SOL balance on wallet the transaction getting executed and there is no check for this

true, this can be a good feature to add; feel free to contribute and open a PR if you want to implement it!

**Comment by CrispyyBaconx** [comment]
Yeah raydium's list doesn't get updated too frequently and its really inefficient to refresh every time you want new pool data. Was working on a way to fetch keys directly 

in raydiumSwap.ts:
```typescript
    async findPoolInfoForTokens(mintA: string, mintB: string) {
        const base = new PublicKey(mintA);
        const quote = new PublicKey(mintB);

        const accounts = await this.fetchOpenBookAccounts(base, quote);

        if (accounts.length === 0) {
            console.log("No pool found for the given token pair."); 
            return null;
        }

        const marketAccount = await this.connection.getAccountInfo(accounts[0].marketId);
        if (!marketAccount) {
            console.log("Market account not found.");
            return null;
        }
        const marketInfo = MARKET_STATE_LAYOUT_V3.decode(marketAccount.data);

        const poolKeys = jsonInfo2PoolKeys({
            id: accounts[0].id,
            baseMint: accounts[0].baseMint.toString(),
            quoteMint: accounts[0].quoteMint.toString(),
            lpMint: accounts[0].lpMint.toString(),
            baseDecimals: accounts[0].baseDecimal,
            quoteDecimals: accounts[0].quoteDecimal,
            version: 4,
            programId: accounts[0].owner.toString(),
            authority: Liquidity.getAssociatedAuthority({ programId: accounts[0].owner }).publicKey.toString(),
            openOrders: accounts[0].openOrders.toString(),
            targetOrders: accounts[0].targetOrders.toString(),
            baseVault: accounts[0].baseVault.toString(),
            quoteVault: accounts[0].quoteVault.toString(),
            withdrawQueue: accounts[0].withdrawQueue.toString(),
            lpVault: accounts[0].lpVault.toString(),
            marketVersion: 3,
            marketProgramId: accounts[0].marketProgramId.toString(),
            marketId: accounts[0].marketId.toString(),
            marketAuthority: Market.getAssociatedAuthority({ programId: accounts[0].marketProgramId, marketId: accounts[0].marketId }).publicKey.toString(),
            marketBaseVault: marketInfo.baseVault.toString(),
            marketQuoteVault: marketInfo.quoteVault.toString(),
            marketBids: marketInfo.bids.toString(),
            marketAsks: marketInfo.asks.toString(),
            marketEventQueue: marketInfo.eventQueue.toString(),
            lookupTableAccount: PublicKey.default.toString()    
        }) as LiquidityPoolKeys;

        console.log(poolKeys)

        return poolKeys;
    }

    async fetchOpenBookAccounts(base: PublicKey, quote: PublicKey) {
        const accounts = await this.connection.getProgramAccounts(
            networkData.openbookProgramId,
            {
                commitment: 'confirmed',
                filters: [
                    { dataSize: MARKET_STATE_LAYOUT_V3.span },
                    {
                        memcmp: {
                            offset: MARKET_STATE_LAYOUT_V3.offsetOf("baseMint"),
                            bytes: base.toBase58(),
                        },
                    },
                    {
                        memcmp: {
                            offset: MARKET_STATE_LAYOUT_V3.offsetOf("quoteMint"),
                            bytes: quote.toBase58(),
                        },
                    },
                ],
            }
        );

        return accounts.map(({ pubkey, account }) => ({
            id: pubkey.toString(),
            ...LIQUIDITY_STATE_LAYOUT_V4.decode(account.data),
        }));
    }
```

seems the openbook account is being found, and everything looks good up until you try to simulate the tx, which is where im getting an error

**Comment by AMIYA8597** [comment]
> hello. I don't know why it gives me this error when I exceute the swap. this error related to the pool and it's like the code can't read the pool list.
> 
> Loaded pool keys C:\raydium-sdk-swap-example-typescript\src\RaydiumSwap.ts:59 const poolData = this.allPoolKeysJson.find( ^ TypeError: Cannot read properties of undefined (reading 'find') at RaydiumSwap.findPoolInfoForTokens (C:\raydium-sdk-swap-example-typescript\src\RaydiumSwap.ts:59:43) at C:\raydium-sdk-swap-example-typescript\src\index.ts:30:32 at Generator.next () at fulfilled (C:\raydium-sdk-swap-example-typescript\src\index.ts:5:58) at processTicksAndRejections (node:internal/process/task_queues:95:5) error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.






here I am facing other error 

    throw new Error('Non-base' + BASE + ' character')
          ^
Error: Non-base58 character

**Comment by brianyeap** [comment]
> > Guys thanks a lot for your helps. Is there any way to test it first on devnet ?
> > Why my change "https://api.raydium.io/v2/sdk/liquidity/devnet.json" not works ? @soos3d could you please let me know how can i make the code compatible for Devnet ?
> > Doing test by Devnet is important really.
> 
> Let me look into that!

i have this issue to, is it becasue raydium does not provide the poolkeys?

**Comment by alexandr-kazakov** [comment]
I'm searching myself ho to make swap for newly created coins. Current this repo solution doesn't work for this.
I implemented this  https://solana.stackexchange.com/a/10020/2840 by LIQUIDITY_STATE_LAYOUT_V4 solution too and it doesn't help. I'm thinking about yellowstone-grpc solution now.

Any ideas?

**Comment by brooke007** [comment]
> Hey folks 👋 I have same issue. I'm trying to get pool information from here `https://api.raydium.io/v2/sdk/liquidity/mainnet.json` and seems Raydium is updating file not so frequently and one can't get latest deployed pool information from there. Do you know any alternative services that provide that?

have you solved it?

**Comment by alexandr-kazakov** [comment]
@brooke007 I solved it https://github.com/alexandr-kazakov/solana-crendel-bot In my bot pools data is not get from mainnet.json. From the first second of pool creation you will know about it.
