### ISSUE TITLE
No Transaction found in Chainstack RPC & No Transaction in Solscan even after successfully swapped !

### ISSUE THREAD

**Issue by anisurrahman072** [chainstacklabs/raydium-sdk-swap-example-typescript#5]
Hi @soos3d, I have seen exactly a same output like your one 👇

https://github.com/chainstacklabs/raydium-sdk-swap-example-typescript/issues/2#issuecomment-2012547797

It seems like the transaction was succeeded but no effect on Solscan & even in Chainstack i don't see any transaction that was passed (0 passed 0 failed). But the log in terminal seems like OK as like as your response in the link above.

I had **0.01 SOL** in my account & wanted to SWAP **0.0001 SOL**. Below is the config of SWAP 👇

<img width="1022" alt="Screenshot 2024-04-02 at 3 07 29 PM" src="https://github.com/chainstacklabs/raydium-sdk-swap-example-typescript/assets/40535268/356bfb84-7bbc-4a65-9dfe-06af64227fa8">

Finally nothing swapped !!! My main account balance was **0.01 SOL** & still that is **0.01 SOL**. No change in any end !!!

Could you please help me on this  @soos3d ?

**Comment by datacoder-io** [comment]
Same issue

**Comment by Krshivam25** [comment]
I have same issue I swapped the token using the RPC node and its not coming in
[SOLSCAN](https://solscan.io/tx/MHsDbkop1UE1rpKY8NmaT5HwzHHzRJf5yS9K7DMNy7kHTnv2g9CjFRCstrzjvtaBkvZVBuh1si28qTC9kXXvTfR)

**Comment by soos3d** [comment]
yeah this happens when the chain is really congested; the transactions are simply dropped. Unfortunately, there is not too much we can do at the moment besides increasing priority fees (the `maxLamports` parameter in `swapConfig`) and send transactions continuously until one goes through🥲

I'm looking into editing the code a bit to improve the chances.

**Comment by datacoder-io** [comment]
You must spamming until the tx confirmed

**Comment by anisurrahman072** [comment]
> yeah this happens when the chain is really congested; the transactions are simply dropped. Unfortunately, there is not too much we can do at the moment besides increasing priority fees (the `maxLamports` parameter in `swapConfig`) and send transactions continuously until one goes through🥲
> 
> I'm looking into editing the code a bit to improve the chances.

Ohhh now I'm again facing the ISSUE. After completed SWAP I see a Transaction Id. But that is a fake transaction link on Solscan !!!!! 

My thought from ethereum is that, if transaction failed then that transaction must show in Solscan that transaction failed with a reason !!!

**Comment by anisurrahman072** [comment]
I'm thinking anything happened to Chainstack RPC !? It was working days before today 😵‍💫

**Comment by soos3d** [comment]
yeah, unfortunately, Solana is super busy, and a lot of transactions are dropped before being confirmed. They are working on a fix for this and will hopefully be released soon!
